name: Deploy infrastructure of Heimdall to google cloud

on:
  push:
    branches:
      - main

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_STACK_NAME: ${{ secrets.STACK_NAME }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GIT_REPO: ${{ github.repository }}
  PULUMI_WORKING_DIRECTORY: ./infra/heimdall

jobs:
  deploy:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.WORKLOAD_POOL }}/providers/${{ secrets.WORKLOAD_PROVIDER }}'
          service_account: 'pulumi@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - run: go mod download
        working-directory: ${{ env.PULUMI_WORKING_DIRECTORY }}

      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: ${{ secrets.PULUMI_STACK_NAME }}
          work-dir: ${{ env.PULUMI_WORKING_DIRECTORY }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}